### ISSUE TITLE
Bootkali issue

### ISSUE THREAD

**Issue by Th3-A6add0n** [atarii/Magisk_Kali_Nethunter#11]
> 127|:/ # bootkali                                                
> Mounting kali chroot...
> mount: mounting /sdcard/kali-chroot.img on /data/local/nhsystem/kali-armhf failed: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armhf/etc/resolv.conf: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armhf/etc/resolv.conf: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armhf/etc/resolv.conf: No such file or directory
> /system/bin/bootkali: /data/data/com.offsec.nethunter/files/scripts/bootkali_init[268]: can't create /data/local/nhsystem/kali-armchroot: can't execute '/bin/bash': No such file or directory

**Comment by sumit7577** [comment]
Same here.please help

**Comment by Th3-A6add0n** [comment]
> Same here.please help

use kalifs-armhf
https://build.nethunter.com/kalifs/kalifs-latest/
