### ISSUE TITLE
s8+ phone reboots once I try to use Terminal

### ISSUE THREAD

**Issue by bozwald** [atarii/Magisk_Kali_Nethunter#2]
I flashed TWRP onto my S8+ SM-G955F via odin, flashed the no-verity zip, flashed magisk latest version, loaded up then added the nethunter module, downloaded chroot, then when i enter terminal my phone resets, tried to install busybox in various ways, osmosis and nethunter and busybox pro, but not sure why my phone reboots, ive managed to corrupt the stock boot and I need to reflash stock rom now but could someone look into this?

**Comment by bozwald** [comment]
for additional information, I tried to su bootkali in another terminal app, I've tried to find other versions of chroot, the minimal client fails hash check, the full downloads but gives me reboot, and using the files by SD card also doesnt work hope this helps

**Comment by DanielL99** [comment]
As I know Nethunter needs SELinux set to permissive
Maybe it could help to change it
Here is a magisk module, which changes it on every start:
[https://forum.xda-developers.com/apps/magisk/module-magisk-selinux-permissive-script-t3577549](url)

**Comment by bozwald** [comment]
Thats correct, we had

**Comment by bozwald** [comment]
Thanks I hadnt updated this ticket I had to remount the system as rw
