### ISSUE TITLE
AVAST flagged as malware

### ISSUE THREAD

**Issue by krooked-1** [atarii/Magisk_Kali_Nethunter#3]
That pretty much sums it up, my AVAST antivirus software flagged it as malware and aborted the connection.

**Comment by DanielL99** [comment]
This is normal, because nethunter installs apps like csploit, which gets recognized as malware
You should get the same problem, when you install the official nethunter package
So no worry, deactivate your antivirus software for some minutes and try it again

**Comment by atarii** [comment]
Thanks Daniel, yes this is because of the nature of files inside Kali Nethunter.

**Comment by krooked-1** [comment]
I should have known better. Thanks guys
