### ISSUE TITLE
Apps not Launching

### ISSUE THREAD

**Issue by thehappydinoa** [atarii/Magisk_Kali_Nethunter#6]
Hi,

I love your project but I am having a few issues. Everytime I go to create a Kali terminal the terminal app crashes. This also happens when I try to start the vnc server. I am running Android 8.0.0 on my Essential Phone (arm64) using Magisk 15.3.

Thanks

**Comment by sashaman** [comment]
you need to enable ssh service before you are able to connect kali term or else it crashes, same issue with "normal" installation
