### ISSUE TITLE
Kali chroot manager 

### ISSUE THREAD

**Issue by kendallgreen** [atarii/Magisk_Kali_Nethunter#7]
I am trying to reinstall Nethunter v6 on TugaPower V23.  I had it working on v5 and v21.  I first tried to install nethunter v6 which left me at "New installation log file: Storage/emulated/0/nh_install ... 
I then removed nethunter v5 and installed v6.  Occasionally I get "eveerything went fine chroot is installed"
When I try "install and update" I get a terminal but nothing else happens.

**Comment by thehappydinoa** [comment]
Ya the updater is broken, Google how to install kali-chroot for your device.

**Comment by kendallgreen** [comment]
closed
