### ISSUE TITLE
Kali terminal

### ISSUE THREAD

**Issue by Th3-A6add0n** [atarii/Magisk_Kali_Nethunter#9]
I've installed Kali Chroot full (downloaded from the site itself) but whenever I open terminal and select Kali, it runs something and closes itself in a second.
I don't know what's happening.

It was so fast, I couldn't take the screenshot, so here's [screen recording](https://drive.google.com/file/d/1R6bTV7Gm4bfEe1TTg52z-MDM3BlkbvL8/view?usp=drivesdk)

**Comment by huitc** [comment]
normal thing? (me2

**Comment by thehappydinoa** [comment]
This means Kali is not running.  Try `bootkali`: https://github.com/offensive-security/kali-nethunter/issues/420#issuecomment-204835143

**Comment by Th3-A6add0n** [comment]
> This means Kali is not running. Try `bootkali`: [offensive-security/kali-nethunter#420 (comment)](https://github.com/offensive-security/kali-nethunter/issues/420#issuecomment-204835143)

Did that, doesn't work either.

**Comment by Th3-A6add0n** [comment]
> This means Kali is not running. Try `bootkali`: [offensive-security/kali-nethunter#420 (comment)](https://github.com/offensive-security/kali-nethunter/issues/420#issuecomment-204835143)

Got anything??
